"use client";

import {useEffect,useMemo,useState} from "react";
import {BookOpen,CalendarDays,Check,ChevronDown,ChevronUp,Clipboard,Dumbbell,HelpCircle,History,Minus,Pencil,Plus,RefreshCw,Search,Trash2,Users,X} from "lucide-react";
import {EXAM_GROUPS,GRADES,KATAS,Kata,Grade,bandText} from "./data";

type Log={id:string;date:string;session?:number;status:"완료"|"취소";participants:Grade[];katas:Kata[];note:string;createdAt:string};
type StoredLog=Log&{plannedGrades?:Grade[];actualGrades?:Grade[];participants?:Grade[]};
type Tab="today"|"logs"|"hombu"|"exam"|"help";
const KEY="samsungdang-class-manager-v1",today=new Date().toISOString().slice(0,10);
const TECH_ORDER=["1교","2교","3교","4교","5교","입신던지기","사방던지기","손목뒤집기","천지던지기","회전던지기","호흡던지기","입기 호흡법","십자던지기"];

function normalizedLogs(raw:StoredLog[]):Log[]{return(raw??[]).map(l=>({...l,participants:l.participants??l.actualGrades??l.plannedGrades??[]}))}
function loadState():{logs:Log[];lastSession:number}{if(typeof window==="undefined")return{logs:[],lastSession:1010};try{const s=JSON.parse(localStorage.getItem(KEY)||""),logs=normalizedLogs(s.logs),completed=logs.filter(l=>l.status==="완료"&&l.session);if(!completed.length)return{logs,lastSession:1010};return{logs,lastSession:Math.max(1010,s.lastSession??1010,...completed.map(l=>l.session??1010))}}catch{return{logs:[],lastSession:1010}}}
function groupOf(k:Kata){if(k.technique==="내회전던지기"||k.technique==="외회전던지기")return"회전던지기";if(k.technique==="호흡법")return"입기 호흡법";return k.technique}
const PICKER_KATAS=KATAS.filter(k=>(k.area==="일반 체술"||k.area==="호흡력")&&k.name!=="좌기 호흡법").sort((a,b)=>{const ai=TECH_ORDER.indexOf(groupOf(a)),bi=TECH_ORDER.indexOf(groupOf(b));return(ai<0?99:ai)-(bi<0?99:bi)||a.name.localeCompare(b.name,"ko")});
function recommend(grades:Grade[],count:number,logs:Log[]):Kata[]{if(!grades.length)return[];const highest=Math.min(...grades),recent=logs.filter(l=>l.status==="완료").slice(0,10).flatMap(l=>l.katas.map(k=>k.name));const scored=PICKER_KATAS.filter(k=>k.hombu&&(!k.grade||k.grade>=highest)).map(k=>({k,score:30+(k.exam?20:0)+(k.grade===highest?16:0)+(k.form!=="입기"?14:0)-recent.filter(n=>n===k.name).length*18+(k.links.length?2:0)})).sort((a,b)=>b.score-a.score||TECH_ORDER.indexOf(groupOf(a.k))-TECH_ORDER.indexOf(groupOf(b.k))||a.k.name.localeCompare(b.k.name,"ko")),out:Kata[]=[];for(const x of scored){if(out.filter(k=>k.technique===x.k.technique).length>=2||out.filter(k=>k.attack===x.k.attack).length>=2)continue;out.push(x.k);if(out.length===count)break}return out}
function counts(items:string[]){return items.reduce<Record<string,number>>((a,v)=>(a[v]=(a[v]||0)+1,a),{})}
function summary(c:Record<string,number>){return Object.entries(c).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`${k} ${v}`).join(" · ")||"없음"}
function gradeText(g:Grade[]){return g.map(x=>`${x}급`).join(" · ")||"없음"}
function customKata(raw:string):Kata{const name=raw.trim(),form=name.startsWith("좌기 ")?"좌기":name.startsWith("반신반립 ")?"반신반립":"입기";const technique=["합기떨어뜨리기","외회전던지기","내회전던지기","입신던지기","사방던지기","손목뒤집기","천지던지기","회전던지기","허리던지기","호흡던지기","십자던지기","구석던지기","호흡법","5교","4교","3교","2교","1교"].find(v=>name.includes(v))??"확장·보조";const clean=name.replace(/^(좌기|반신반립) /,"");const attack=technique==="확장·보조"?"직접 입력":clean.slice(0,Math.max(0,clean.lastIndexOf(` ${technique}`)))||"직접 입력";return{id:`custom-${crypto.randomUUID()}`,name,form,attack,technique,area:"일반 체술",hombu:false,exam:false,links:[]}}

function GradePicker({value,onChange}:{value:Grade[];onChange:(g:Grade[])=>void}){return <div><div className="field-label">참가 급수</div><div className="grade-row">{GRADES.map(g=><button key={g} className={value.includes(g)?"grade active":"grade"} onClick={()=>onChange(value.includes(g)?value.filter(x=>x!==g):[...value,g].sort((a,b)=>b-a) as Grade[])}>{g}급</button>)}</div></div>}
function KataOptions(){const used=new Set<string>();return <>{TECH_ORDER.map(group=>{const list=PICKER_KATAS.filter(k=>groupOf(k)===group);list.forEach(k=>used.add(k.id));return list.length?<optgroup key={group} label={group}>{list.map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</optgroup>:null})}<optgroup label="기타">{PICKER_KATAS.filter(k=>!used.has(k.id)).map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</optgroup></>}
function KataCard({kata,index,total,onMove,onRemove,onReplace}:{kata:Kata;index:number;total:number;onMove:(d:-1|1)=>void;onRemove:()=>void;onReplace:(id:string)=>void}){return <article className="kata-card"><div className="kata-index">{index+1}</div><div className="kata-body"><strong>{kata.name}</strong><div className="tags"><span>{kata.form}</span><span>{kata.technique}</span>{kata.exam&&<span className="blue">{kata.grade}급 심사</span>}{kata.links.length>0&&<span className="green">영상 {kata.links.length}</span>}</div><select aria-label={`${kata.name} 교체`} value={kata.id} onChange={e=>onReplace(e.target.value)}><KataOptions/></select></div><div className="icon-stack"><button disabled={index===0} onClick={()=>onMove(-1)} aria-label="위로"><ChevronUp/></button><button disabled={index===total-1} onClick={()=>onMove(1)} aria-label="아래로"><ChevronDown/></button><button className="danger" onClick={onRemove} aria-label="삭제"><Trash2/></button></div></article>}

function Analysis({log,logs}:{log:Log;logs:Log[]}){
 if(log.status==="취소")return <div className="analysis canceled-analysis"><strong>취소 수업</strong><p>실시하지 않은 일정이므로 회차와 누적 분석에서 제외됩니다.</p></div>;
 const forms=counts(log.katas.map(k=>k.form)),attacks=counts(log.katas.map(k=>k.attack)),techniques=counts(log.katas.map(k=>k.technique));
 const pins=log.katas.filter(k=>/^[1-5]교$/.test(k.technique)).length,throws=log.katas.filter(k=>!(/^[1-5]교$/.test(k.technique))&&k.technique!=="호흡법").length;
 const warnings:string[]=[];if(!forms["좌기"]&&!forms["반신반립"])warnings.push("입기만 포함됨");if(!pins||!throws)warnings.push("교 계열과 던지기 계열 중 한쪽이 없음");if(Math.max(...Object.values(attacks))>Math.ceil(log.katas.length/2))warnings.push("특정 공격형태 비중이 높음");
 const verdict=warnings.length>=2?"보완 필요":warnings.length===1?"약한 편중":"정상 순환";
 const next=recommend(log.participants,5,logs.filter(l=>l.id!==log.id)).filter(k=>!log.katas.some(x=>x.id===k.id)).slice(0,5);
 return <div className="analysis" onClick={e=>e.stopPropagation()}><section><h4>1. 오늘 수업 요약</h4><div className="analysis-grid"><span>수업일<strong>{log.date}</strong></span><span>수업회차<strong>{log.session}차</strong></span><span>참가 급수<strong>{gradeText(log.participants)}</strong></span><span>카타 수<strong>{log.katas.length}개</strong></span></div></section><section><h4>2. 카타별 분석</h4><div className="analysis-katas">{log.katas.map(k=><div key={k.id}><strong>{k.name}</strong><span>{k.form} · {k.attack} · {k.technique}</span><small>{k.hombu?"본부 기본 카타":"본부 연계·확장"} / {k.exam?`${k.grade}급 심사 직접 대응`:"삼성당 심사표 외"}</small></div>)}</div></section><section><h4>3. 본부·심사범위</h4><p>본부 기본 카타 {log.katas.filter(k=>k.hombu).length}/{log.katas.length}개 · 삼성당 심사표 직접 대응 {log.katas.filter(k=>k.exam).length}/{log.katas.length}개</p><p>9~8급 기초 직접 포함: {log.katas.some(k=>k.grade===8||k.grade===9)?"있음":"없음"}</p></section><section><h4>4. 편중 분석</h4><p>형태: {summary(forms)}</p><p>공격형태: {summary(attacks)}</p><p>대응기술: {summary(techniques)}</p><p>교 계열 {pins} · 던지기 계열 {throws}</p>{warnings.length>0&&<ul>{warnings.map(w=><li key={w}>{w}</li>)}</ul>}</section>{log.note&&<section><h4>5. 수업 메모·회원별 보완</h4><p className="pre">{log.note}</p></section>}<section><h4>{log.note?"6":"5"}. 다음 수업 보완 후보</h4><ol>{next.map(k=><li key={k.id}>{k.name}<small>{k.form}·{k.technique} 순환 보완</small></li>)}</ol></section><section className={`verdict ${verdict==="정상 순환"?"good":"warn"}`}><h4>종합 판단</h4><strong>{verdict}</strong><p>본부 기본 카타, 심사범위, 형태, 공격형태, 교·던지기 계열을 종합한 규칙 기반 초안입니다.</p></section></div>
}

export default function Home(){
 const[tab,setTab]=useState<Tab>("today"),[date,setDate]=useState(today),[participants,setParticipants]=useState<Grade[]>([9,7,5,2]),[generatedParticipants,setGeneratedParticipants]=useState<Grade[]|null>(null),[count,setCount]=useState(5),[plan,setPlan]=useState<Kata[]>([]),[note,setNote]=useState(""),[logs,setLogs]=useState<Log[]>([]),[lastSession,setLastSession]=useState(1010),[query,setQuery]=useState(""),[examGrade,setExamGrade]=useState<Grade>(7),[toast,setToast]=useState(""),[editingId,setEditingId]=useState<string|null>(null),[deleteId,setDeleteId]=useState<string|null>(null),[expandedId,setExpandedId]=useState<string|null>(null),[showAdd,setShowAdd]=useState(false),[addChoice,setAddChoice]=useState(PICKER_KATAS[0]?.id??""),[customName,setCustomName]=useState("");
 useEffect(()=>{const id=window.setTimeout(()=>{const s=loadState();setLogs(s.logs);setLastSession(s.lastSession)},0);return()=>window.clearTimeout(id)},[]);useEffect(()=>{if(logs.length||lastSession!==1010)localStorage.setItem(KEY,JSON.stringify({logs,lastSession}))},[logs,lastSession]);useEffect(()=>{if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>undefined)},[]);
 function notify(m:string){setToast(m);window.setTimeout(()=>setToast(""),2200)}function generate(){setPlan(recommend(participants,count,logs));setGeneratedParticipants([...participants]);notify("참가 급수 기준으로 구성했습니다.")}
 function changeCount(d:number){const n=Math.max(1,Math.min(10,count+d));setCount(n);if(plan.length){setPlan(recommend(participants,n,logs));setGeneratedParticipants([...participants]);notify(`${n}개 카타로 재구성했습니다.`)}}function move(i:number,d:-1|1){const c=[...plan],t=i+d;[c[i],c[t]]=[c[t],c[i]];setPlan(c)}function replace(i:number,id:string){const k=KATAS.find(x=>x.id===id);if(!k)return;const c=[...plan];c[i]=k;setPlan(c)}function addSelected(){const k=PICKER_KATAS.find(x=>x.id===addChoice);if(!k)return;setPlan([...plan,k]);setCount(plan.length+1);setShowAdd(false)}function addCustom(){if(!customName.trim())return notify("직접 입력할 카타명을 작성하십시오.");setPlan([...plan,customKata(customName)]);setCount(plan.length+1);setCustomName("");setShowAdd(false);notify("확장·보조 카타로 추가했습니다.")}
 function resetEditor(){setEditingId(null);setDate(today);setParticipants([9,7,5,2]);setGeneratedParticipants(null);setPlan([]);setCount(5);setNote("");setShowAdd(false);setCustomName("")}
 function save(status:"완료"|"취소"){if(editingId){const original=logs.find(l=>l.id===editingId);if(!original)return;if(original.status==="완료"&&!plan.length)return notify("완료 일지에는 한 개 이상의 카타가 필요합니다.");setLogs(logs.map(l=>l.id===editingId?{...l,date,participants,katas:l.status==="완료"?plan:[],note}:l));notify(`${original.session?`${original.session}차 `:"취소 "}일지를 수정했습니다.`);setEditingId(null);setTab("logs");return}if(status==="완료"&&!plan.length)return notify("먼저 수업 카타를 구성하십시오.");const session=status==="완료"?lastSession+1:undefined,log:Log={id:crypto.randomUUID(),date,session,status,participants,katas:status==="완료"?plan:[],note,createdAt:new Date().toISOString()};setLogs([log,...logs]);if(session)setLastSession(session);notify(status==="완료"?`${session}차 수업일지로 저장했습니다.`:"취소 일정으로 저장했습니다. 회차는 증가하지 않습니다.");setTab("logs")}
 function editLog(log:Log){setEditingId(log.id);setDate(log.date);setParticipants(log.participants);setGeneratedParticipants([...log.participants]);setPlan(log.katas);setCount(log.katas.length||5);setNote(log.note);setTab("today")}
 function deleteLog(id:string){const remaining=logs.filter(l=>l.id!==id),completed=remaining.filter(l=>l.status==="완료"&&l.session);setLogs(remaining);setLastSession(completed.length?Math.max(1010,...completed.map(l=>l.session??1010)):1010);setDeleteId(null);setExpandedId(null);notify("수업일지를 삭제하고 최근 완료회차를 다시 계산했습니다.")}
 async function copyLog(log:Log){if(!log.session)return;await navigator.clipboard.writeText(bandText(log.date,log.session,log.katas));notify("밴드용 수업일지를 복사했습니다.")}function exportData(){const b=new Blob([JSON.stringify({logs,lastSession},null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`삼성당-수업관리-${today}.json`;a.click();URL.revokeObjectURL(u)}
 const changed=!!plan.length&&!!generatedParticipants&&generatedParticipants.join()!==participants.join(),curriculum=useMemo(()=>KATAS.filter(k=>k.hombu&&(k.name.includes(query)||k.technique.includes(query)||k.attack.includes(query))),[query]),nav=[{id:"today",label:"수업구성",icon:CalendarDays},{id:"logs",label:"수업일지",icon:History},{id:"hombu",label:"본부 카타",icon:BookOpen},{id:"exam",label:"삼성당 심사표",icon:Dumbbell},{id:"help",label:"사용법",icon:HelpCircle}] as const;
 return <main className="app-shell"><header className="topbar"><div><p>AIKIDO SAMSUNGDANG</p><h1>수업관리</h1></div><div className="session-chip"><span>최근 완료</span><strong>{lastSession}차</strong></div></header><section className="content">
 {tab==="today"&&<div className="stack">{editingId&&<div className="edit-banner"><Pencil/><div><strong>수업일지 수정 중</strong><span>회차와 완료·취소 상태는 유지됩니다.</span></div><button onClick={resetEditor}>수정 취소</button></div>}<section className="panel hero-panel"><div><span className="eyebrow">{editingId?"기록 수정":"새 수업 구성"}</span><h2>참가자에 맞춰 기본 카타를 고릅니다</h2></div><label className="date-field"><span>수업일</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></section><section className="panel"><GradePicker value={participants} onChange={setParticipants}/>{changed&&<div className="attendance-alert"><Users/><div><strong>참가자 구성이 변경되었습니다.</strong><span>기존안은 유지됩니다. 변경된 참가 급수로 다시 구성할 수 있습니다.</span></div><button onClick={generate}><RefreshCw/>재구성</button></div>}</section><section className="panel"><div className="section-head"><div><span className="eyebrow">수업구성안</span><h2>{plan.length?`${plan.length}개 카타`:editingId?"카타 없음":"아직 구성하지 않았습니다"}</h2></div><div className="counter"><button onClick={()=>changeCount(-1)}><Minus/></button><strong>{count}</strong><button onClick={()=>changeCount(1)}><Plus/></button></div></div>{!plan.length&&!editingId?<button className="primary large" disabled={!participants.length} onClick={generate}><Dumbbell/>수업구성안 산출</button>:<><div className="kata-list">{plan.map((k,i)=><KataCard key={`${k.id}-${i}`} kata={k} index={i} total={plan.length} onMove={d=>move(i,d)} onRemove={()=>setPlan(plan.filter((_,x)=>x!==i))} onReplace={id=>replace(i,id)}/>)}</div>{(!editingId||logs.find(l=>l.id===editingId)?.status==="완료")&&<><button className="ghost full" onClick={()=>setShowAdd(!showAdd)}><Plus/>{showAdd?"추가 닫기":"카타 추가"}</button>{showAdd&&<div className="add-panel"><label><span>등록된 카타</span><select value={addChoice} onChange={e=>setAddChoice(e.target.value)}><KataOptions/></select></label><button className="secondary-add" onClick={addSelected}>선택 카타 추가</button><div className="add-divider"><span>목록에 없는 카타</span></div><label><span>카타명 직접 입력</span><input value={customName} onChange={e=>setCustomName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")addCustom()}} placeholder="예: 정면타 6교"/></label><button className="custom-add" onClick={addCustom}>확장·보조 카타로 추가</button></div>}</>}</>}</section>{(plan.length>0||editingId)&&<section className="panel"><label className="field-label" htmlFor="note">수업 메모</label><textarea id="note" value={note} onChange={e=>setNote(e.target.value)} placeholder="수업 주제, 회원별 보완사항, 실제 변경 내용을 기록합니다."/><div className={editingId?"action-grid single":"action-grid"}><button className="primary" onClick={()=>save("완료")}><Check/>{editingId?"수정사항 저장":"실시·일지 저장"}</button>{!editingId&&<button className="cancel" onClick={()=>save("취소")}><X/>수업 취소</button>}</div></section>}</div>}
 {tab==="logs"&&<div className="stack"><div className="page-title"><span className="eyebrow">수업일지</span><h2>완료와 취소 기록</h2><p>일지를 누르면 수업구성 분석을 확인할 수 있습니다.</p></div>{!logs.length?<div className="empty"><History/><strong>저장된 수업일지가 없습니다.</strong></div>:logs.map(log=><article className={`panel log-card ${expandedId===log.id?"expanded":""}`} key={log.id} onClick={()=>setExpandedId(expandedId===log.id?null:log.id)}><div className="log-head"><div><span className={log.status==="완료"?"status done":"status canceled"}>{log.status}</span><h3>{log.date} {log.session?`· ${log.session}차`:"· 회차 미반영"}</h3></div><div className="log-actions">{log.session&&<button className="copy" onClick={e=>{e.stopPropagation();copyLog(log)}}><Clipboard/><span>복사</span></button>}<button className="edit" onClick={e=>{e.stopPropagation();editLog(log)}}><Pencil/><span>수정</span></button><button className="delete" onClick={e=>{e.stopPropagation();setDeleteId(log.id)}}><Trash2/><span>삭제</span></button></div></div><div className="log-grades"><span>참가 {gradeText(log.participants)}</span></div>{log.katas.length>0&&<ol>{log.katas.map(k=><li key={k.id}>{k.name}{k.links.length>0&&<span>영상 {k.links.length}</span>}</li>)}</ol>}{log.note&&<p className="note">{log.note}</p>}{deleteId===log.id&&<div className="delete-confirm" onClick={e=>e.stopPropagation()}><strong>이 일지를 삭제하시겠습니까?</strong><span>삭제 후 남아 있는 완료 일지를 기준으로 최근 완료회차를 다시 계산합니다.</span><div><button onClick={()=>setDeleteId(null)}>취소</button><button onClick={()=>deleteLog(log.id)}>삭제 확정</button></div></div>}{expandedId===log.id&&<Analysis log={log} logs={logs}/>}<button className="analysis-toggle">{expandedId===log.id?"분석 접기":"수업구성 분석 보기"}<ChevronDown/></button></article>)}</div>}
 {tab==="hombu"&&<div className="stack"><div className="page-title"><span className="eyebrow">현재 등록된 목록</span><h2>본부 카타</h2><p>심사표 포함 여부와 관계없이 기본 카타를 조회합니다.</p></div><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="공격형태·기술·카타 검색"/></label><div className="curriculum-list">{curriculum.map(k=><article className="curriculum-row" key={k.id}><div><strong>{k.name}</strong><span>{k.form} · {k.attack} · {k.technique}</span></div><div className="right-tags">{k.exam?<span className="blue">{k.grade}급</span>:<span>심사표 외</span>}{k.links.length>0&&<span className="green">영상</span>}</div></article>)}</div></div>}
 {tab==="exam"&&<div className="stack"><div className="page-title"><span className="eyebrow">2026. 9. 최종 개정안</span><h2>삼성당 승급심사표</h2><p>선택한 급에서 새로 평가하는 항목입니다. 실제 심사는 하위급 범위를 누적합니다.</p></div><div className="grade-row exam-tabs">{GRADES.map(g=><button key={g} className={examGrade===g?"grade active":"grade"} onClick={()=>setExamGrade(g)}>{g}급</button>)}</div><section className="panel"><div className="exam-summary"><div><span>수련 기준</span><strong>{EXAM_GROUPS[examGrade].sessions}회</strong></div><div><span>중점 기술</span><strong>{EXAM_GROUPS[examGrade].focus}</strong></div></div>{EXAM_GROUPS[examGrade].basics&&<div className="basic-box"><h3>기본동작</h3><div className="tags">{EXAM_GROUPS[examGrade].basics?.map(v=><span key={v}>{v}</span>)}</div></div>}<h3 className="list-title">체술</h3><ol className="exam-list">{EXAM_GROUPS[examGrade].kata.map(name=>{const k=KATAS.find(x=>x.name===name);return <li key={name}><div><strong>{name}</strong><span>{k?.form} · {k?.attack}</span></div>{k?.links.length?<span className="green">영상 {k.links.length}</span>:null}</li>})}</ol></section></div>}
 {tab==="help"&&<div className="stack"><div className="page-title"><span className="eyebrow">앱 정보·사용법</span><h2>삼성당 수업관리</h2><p>본부 기본 카타의 균형 있는 순환과 승급심사 준비를 함께 관리하는 도장장용 도구입니다.</p></div><section className="panel guide"><h3>기본 운영 원칙</h3><p>삼성당 심사표를 따라 본부 카타를 만드는 것이 아니라, 본부 카타를 중심으로 수련하면서 삼성당 심사범위를 아우릅니다.</p><ul><li>본부 기본 카타를 수업 선정의 모체로 사용합니다.</li><li>좌기 호흡법은 매 수업 말미의 고정 수련이므로 구성안에서 제외합니다.</li><li>추천 결과는 지도자가 자유롭게 수정할 수 있습니다.</li></ul></section><section className="panel guide"><h3>수업 전·후</h3><ol><li>수업일과 참가 급수를 선택하고 구성안을 산출합니다.</li><li>참가자가 달라지면 급수를 다시 선택한 뒤 재구성합니다.</li><li>카타 수를 바꾸면 전체 구성안이 새로 산출됩니다.</li><li>완료된 수업은 회차가 증가하고 취소 수업은 누적에서 제외됩니다.</li><li>수업일지를 눌러 분석하고 밴드용 본문을 복사합니다.</li></ol></section><section className="panel guide warning"><h3>데이터 보관</h3><p>초안의 기록은 이 기기에만 저장됩니다. 브라우저 데이터를 삭제하면 기록도 사라질 수 있으므로 정기적으로 백업하십시오.</p><button className="ghost full" onClick={exportData}>수업 데이터 내보내기</button></section><section className="panel guide"><h3>설치</h3><p>안드로이드 Chrome 메뉴에서 ‘홈 화면에 추가’ 또는 ‘앱 설치’를 선택하면 일반 앱처럼 실행할 수 있습니다.</p></section></div>}
 </section><nav className="bottom-nav">{nav.map(({id,label,icon:Icon})=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon/><span>{label}</span></button>)}</nav>{toast&&<div className="toast">{toast}</div>}</main>
}
