"use client";
import {useEffect,useMemo,useState} from "react";
import {BookOpen,CalendarDays,Check,ChevronDown,ChevronUp,Clipboard,Dumbbell,HelpCircle,History,Minus,Plus,RefreshCw,Search,Trash2,Users,X} from "lucide-react";
import {EXAM_GROUPS,GRADES,KATAS,Kata,Grade,bandText} from "./data";
type Log={id:string;date:string;session?:number;status:"완료"|"취소";plannedGrades:Grade[];actualGrades:Grade[];katas:Kata[];note:string;createdAt:string};
type Tab="today"|"logs"|"hombu"|"exam"|"help";const KEY="samsungdang-class-manager-v1",today=new Date().toISOString().slice(0,10);
function loadState():{logs:Log[];lastSession:number}{if(typeof window==="undefined")return{logs:[],lastSession:1010};try{return JSON.parse(localStorage.getItem(KEY)||"")}catch{return{logs:[],lastSession:1010}}}
function recommend(grades:Grade[],count:number,logs:Log[]):Kata[]{if(!grades.length)return[];const highest=Math.min(...grades),recent=logs.filter(l=>l.status==="완료").slice(0,10).flatMap(l=>l.katas.map(k=>k.name));const scored=KATAS.filter(k=>k.hombu&&k.area!=="무기 잡기"&&k.area!=="다인 잡기"&&(!k.grade||k.grade>=highest)).map(k=>({k,score:30+(k.exam?20:0)+(k.grade===highest?16:0)+(k.form!=="입기"?14:0)-recent.filter(n=>n===k.name).length*18+(k.links.length?2:0)})).sort((a,b)=>b.score-a.score||a.k.name.localeCompare(b.k.name,"ko")),out:Kata[]=[];for(const x of scored){if(out.filter(k=>k.technique===x.k.technique).length>=2||out.filter(k=>k.attack===x.k.attack).length>=2)continue;out.push(x.k);if(out.length===count)break}return out}
function GradePicker({value,onChange,label}:{value:Grade[];onChange:(g:Grade[])=>void;label:string}){return <div><div className="field-label">{label}</div><div className="grade-row">{GRADES.map(g=><button key={g} className={value.includes(g)?"grade active":"grade"} onClick={()=>onChange(value.includes(g)?value.filter(x=>x!==g):[...value,g].sort((a,b)=>b-a) as Grade[])}>{g}급</button>)}</div></div>}
function KataCard({kata,index,total,onMove,onRemove,onReplace}:{kata:Kata;index:number;total:number;onMove:(d:-1|1)=>void;onRemove:()=>void;onReplace:(id:string)=>void}){return <article className="kata-card"><div className="kata-index">{index+1}</div><div className="kata-body"><strong>{kata.name}</strong><div className="tags"><span>{kata.form}</span><span>{kata.technique}</span>{kata.exam&&<span className="blue">{kata.grade}급 심사</span>}{kata.links.length>0&&<span className="green">영상 {kata.links.length}</span>}</div><select aria-label={`${kata.name} 교체`} value={kata.id} onChange={e=>onReplace(e.target.value)}>{KATAS.filter(k=>k.area==="일반 체술"||k.area==="호흡력").map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</select></div><div className="icon-stack"><button disabled={index===0} onClick={()=>onMove(-1)} aria-label="위로"><ChevronUp/></button><button disabled={index===total-1} onClick={()=>onMove(1)} aria-label="아래로"><ChevronDown/></button><button className="danger" onClick={onRemove} aria-label="삭제"><Trash2/></button></div></article>}
export default function Home(){
 const[tab,setTab]=useState<Tab>("today"),[date,setDate]=useState(today),[plannedGrades,setPlannedGrades]=useState<Grade[]>([9,7,5,2]),[actualGrades,setActualGrades]=useState<Grade[]>([9,7,5,2]),[count,setCount]=useState(5),[plan,setPlan]=useState<Kata[]>([]),[note,setNote]=useState(""),[logs,setLogs]=useState<Log[]>([]),[lastSession,setLastSession]=useState(1010),[query,setQuery]=useState(""),[examGrade,setExamGrade]=useState<Grade>(7),[toast,setToast]=useState("");
 useEffect(()=>{const id=window.setTimeout(()=>{const s=loadState();setLogs(s.logs);setLastSession(s.lastSession)},0);return()=>window.clearTimeout(id)},[]);useEffect(()=>{if(logs.length||lastSession!==1010)localStorage.setItem(KEY,JSON.stringify({logs,lastSession}))},[logs,lastSession]);useEffect(()=>{if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>undefined)},[]);
 function notify(m:string){setToast(m);window.setTimeout(()=>setToast(""),2200)}function generate(actual=false){setPlan(recommend(actual?actualGrades:plannedGrades,count,logs));notify(`${actual?"실제":"예정"} 참가자 기준으로 구성했습니다.`)}function changeCount(d:number){const n=Math.max(1,Math.min(10,count+d));setCount(n);if(plan.length>n)setPlan(plan.slice(0,n))}function move(i:number,d:-1|1){const c=[...plan],t=i+d;[c[i],c[t]]=[c[t],c[i]];setPlan(c)}function replace(i:number,id:string){const k=KATAS.find(x=>x.id===id);if(!k)return;const c=[...plan];c[i]=k;setPlan(c)}function addKata(){const k=KATAS.find(x=>!plan.some(p=>p.id===x.id)&&(x.area==="일반 체술"||x.area==="호흡력"));if(k){setPlan([...plan,k]);setCount(count+1)}}
 function save(status:"완료"|"취소"){if(status==="완료"&&!plan.length)return notify("먼저 수업 카타를 구성하십시오.");const session=status==="완료"?lastSession+1:undefined,log:Log={id:crypto.randomUUID(),date,session,status,plannedGrades,actualGrades,katas:status==="완료"?plan:[],note,createdAt:new Date().toISOString()};setLogs([log,...logs]);if(session)setLastSession(session);notify(status==="완료"?`${session}차 수업일지로 저장했습니다.`:"취소 일정으로 저장했습니다. 회차는 증가하지 않습니다.");setTab("logs")}
 async function copyLog(log:Log){if(!log.session)return;await navigator.clipboard.writeText(bandText(log.date,log.session,log.katas));notify("밴드용 수업일지를 복사했습니다.")}function exportData(){const b=new Blob([JSON.stringify({logs,lastSession},null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`삼성당-수업관리-${today}.json`;a.click();URL.revokeObjectURL(u)}
 const curriculum=useMemo(()=>KATAS.filter(k=>k.hombu&&(k.name.includes(query)||k.technique.includes(query)||k.attack.includes(query))),[query]),nav=[{id:"today",label:"수업",icon:CalendarDays},{id:"logs",label:"일지",icon:History},{id:"hombu",label:"본부",icon:BookOpen},{id:"exam",label:"심사표",icon:Dumbbell},{id:"help",label:"사용법",icon:HelpCircle}] as const;
 return <main className="app-shell"><header className="topbar"><div><p>AIKIDO SAMSUNGDANG</p><h1>수업관리</h1></div><div className="session-chip"><span>최근 완료</span><strong>{lastSession}차</strong></div></header><section className="content">
 {tab==="today"&&<div className="stack"><section className="panel hero-panel"><div><span className="eyebrow">새 수업 구성</span><h2>참가자에 맞춰 기본 카타를 고릅니다</h2></div><label className="date-field"><span>수업일</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></section><section className="panel"><GradePicker label="예정 참가 급수" value={plannedGrades} onChange={g=>{setPlannedGrades(g);setActualGrades(g)}}/><div className="divider"/><GradePicker label="실제 참가 급수" value={actualGrades} onChange={setActualGrades}/>{plannedGrades.join()!==actualGrades.join()&&<div className="attendance-alert"><Users/><div><strong>참가자 구성이 변경되었습니다.</strong><span>기존안은 유지됩니다. 실제 참가자 기준으로 다시 검토할 수 있습니다.</span></div><button onClick={()=>generate(true)}><RefreshCw/>재구성</button></div>}</section><section className="panel"><div className="section-head"><div><span className="eyebrow">수업구성안</span><h2>{plan.length?`${plan.length}개 카타`:"아직 구성하지 않았습니다"}</h2></div><div className="counter"><button onClick={()=>changeCount(-1)}><Minus/></button><strong>{count}</strong><button onClick={()=>changeCount(1)}><Plus/></button></div></div>{!plan.length?<button className="primary large" disabled={!plannedGrades.length} onClick={()=>generate(false)}><Dumbbell/>수업구성안 산출</button>:<><div className="kata-list">{plan.map((k,i)=><KataCard key={`${k.id}-${i}`} kata={k} index={i} total={plan.length} onMove={d=>move(i,d)} onRemove={()=>setPlan(plan.filter((_,x)=>x!==i))} onReplace={id=>replace(i,id)}/>)}</div><button className="ghost full" onClick={addKata}><Plus/>카타 추가</button></>}</section>{plan.length>0&&<section className="panel"><label className="field-label" htmlFor="note">수업 메모</label><textarea id="note" value={note} onChange={e=>setNote(e.target.value)} placeholder="수업 주제, 회원별 보완사항, 실제 변경 내용을 기록합니다."/><div className="action-grid"><button className="primary" onClick={()=>save("완료")}><Check/>실시·일지 저장</button><button className="cancel" onClick={()=>save("취소")}><X/>수업 취소</button></div></section>}</div>}
 {tab==="logs"&&<div className="stack"><div className="page-title"><span className="eyebrow">수업일지</span><h2>완료와 취소 기록</h2><p>완료된 수업만 회차와 누적 분석에 반영됩니다.</p></div>{!logs.length?<div className="empty"><History/><strong>저장된 수업일지가 없습니다.</strong></div>:logs.map(log=><article className="panel log-card" key={log.id}><div className="log-head"><div><span className={log.status==="완료"?"status done":"status canceled"}>{log.status}</span><h3>{log.date} {log.session?`· ${log.session}차`:"· 회차 미반영"}</h3></div>{log.session&&<button className="copy" onClick={()=>copyLog(log)}><Clipboard/>밴드용 복사</button>}</div><div className="log-grades"><span>예정 {log.plannedGrades.map(g=>`${g}급`).join(" · ")||"없음"}</span><span>실제 {log.actualGrades.map(g=>`${g}급`).join(" · ")||"없음"}</span></div>{log.katas.length>0&&<ol>{log.katas.map(k=><li key={k.id}>{k.name}{k.links.length>0&&<span>영상 {k.links.length}</span>}</li>)}</ol>}{log.note&&<p className="note">{log.note}</p>}</article>)}</div>}
 {tab==="hombu"&&<div className="stack"><div className="page-title"><span className="eyebrow">현재 등록된 목록</span><h2>본부 커리큘럼</h2><p>심사표 포함 여부와 관계없이 기본 카타를 조회합니다.</p></div><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="공격형태·기술·카타 검색"/></label><div className="curriculum-list">{curriculum.map(k=><article className="curriculum-row" key={k.id}><div><strong>{k.name}</strong><span>{k.form} · {k.attack} · {k.technique}</span></div><div className="right-tags">{k.exam?<span className="blue">{k.grade}급</span>:<span>심사표 외</span>}{k.links.length>0&&<span className="green">영상</span>}</div></article>)}</div></div>}
 {tab==="exam"&&<div className="stack"><div className="page-title"><span className="eyebrow">2026. 9. 최종 개정안</span><h2>삼성당 승급심사표</h2><p>선택한 급에서 새로 평가하는 항목입니다. 실제 심사는 하위급 범위를 누적합니다.</p></div><div className="grade-row exam-tabs">{GRADES.map(g=><button key={g} className={examGrade===g?"grade active":"grade"} onClick={()=>setExamGrade(g)}>{g}급</button>)}</div><section className="panel"><div className="exam-summary"><div><span>수련 기준</span><strong>{EXAM_GROUPS[examGrade].sessions}회</strong></div><div><span>중점 기술</span><strong>{EXAM_GROUPS[examGrade].focus}</strong></div></div>{EXAM_GROUPS[examGrade].basics&&<div className="basic-box"><h3>기본동작</h3><div className="tags">{EXAM_GROUPS[examGrade].basics?.map(v=><span key={v}>{v}</span>)}</div></div>}<h3 className="list-title">체술</h3><ol className="exam-list">{EXAM_GROUPS[examGrade].kata.map(name=>{const k=KATAS.find(x=>x.name===name);return <li key={name}><div><strong>{name}</strong><span>{k?.form} · {k?.attack}</span></div>{k?.links.length?<span className="green">영상 {k.links.length}</span>:null}</li>})}</ol></section></div>}
 {tab==="help"&&<div className="stack"><div className="page-title"><span className="eyebrow">앱 정보·사용법</span><h2>삼성당 수업관리</h2><p>본부 기본 카타의 균형 있는 순환과 승급심사 준비를 함께 관리하는 도장장용 도구입니다.</p></div><section className="panel guide"><h3>기본 운영 원칙</h3><p>삼성당 심사표를 따라 본부 카타를 만드는 것이 아니라, 본부 카타를 중심으로 수련하면서 삼성당 심사범위를 아우릅니다.</p><ul><li>본부 기본 카타를 수업 선정의 모체로 사용합니다.</li><li>심사표는 참가자별 기술군과 누락 영역을 확인하는 이정표입니다.</li><li>입기·좌기·반신반립, 공격형태, 교·던지기 계열의 편중을 확인합니다.</li><li>추천 결과는 지도자가 자유롭게 수정할 수 있습니다.</li></ul></section><section className="panel guide"><h3>수업 전</h3><ol><li>수업일과 예정 참가 급수를 선택합니다.</li><li>평일 5개, 토요일 7개를 기준으로 카타 수를 조정합니다.</li><li>카타를 교체·삭제·추가하고 순서를 바꿉니다.</li><li>불참자가 생기면 실제 참가 급수를 수정하고 재구성합니다.</li></ol></section><section className="panel guide"><h3>수업 후</h3><ol><li>실제 실시한 카타만 남기고 변경 내용을 수정합니다.</li><li>실시·일지 저장을 누르면 완료 회차가 증가합니다.</li><li>취소 수업은 회차와 누적에 반영되지 않습니다.</li><li>밴드용 복사로 영상 링크가 포함된 본문을 복사합니다.</li></ol></section><section className="panel guide warning"><h3>데이터 보관</h3><p>초안의 기록은 이 기기에만 저장됩니다. 브라우저 데이터를 삭제하면 기록도 사라질 수 있으므로 정기적으로 백업하십시오.</p><button className="ghost full" onClick={exportData}>수업 데이터 내보내기</button></section><section className="panel guide"><h3>설치</h3><p>안드로이드 Chrome 메뉴에서 ‘홈 화면에 추가’ 또는 ‘앱 설치’를 선택하면 일반 앱처럼 실행할 수 있습니다.</p></section></div>}
 </section><nav className="bottom-nav">{nav.map(({id,label,icon:Icon})=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon/><span>{label}</span></button>)}</nav>{toast&&<div className="toast">{toast}</div>}</main>}
